apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: friendviz
spec:
  tls:
  - secretName: friendviz-certs
  rules:
  - host: friendviz.cjblink1.pro
    http:
      paths:
      - backend:
          serviceName: friendviz-service
          servicePort: 80
