---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: friendviz
  annotations:
    flux.weave.works/automated: 'true'
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: friendviz
    spec:
      containers:
      - name: friendviz
        image: 'cjblink1/friendviz:31f0fa61c71fc39813b42d6ff5c18a3f32da10a1'
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: friendviz-service
  labels:
    name: friendviz-service
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: friendviz
  type: ClusterIP

